/**
 * navbar.js — Shared Navigation Bar
 * แก้ไขไฟล์นี้ไฟล์เดียวเพื่ออัปเดต Navbar ทุกหน้าพร้อมกัน
 * ================================================================
 * วิธีเปลี่ยนชื่อ / ไอคอน / เมนู: แก้ที่ตัวแปร NAV_BRAND และ NAV_LINKS ด้านล่าง
 */

(function () {
    // ── แก้ไขได้ที่นี่ ──────────────────────────────────────────
    const NAV_BRAND = {
        name: 'Narin Thongnueadee',   // ชื่อที่แสดงในโลโก้
        icon: '',           // ไอคอนโลโก้ (FontAwesome class)
        href: 'index.html',            // ลิงก์โลโก้
    };

    const NAV_LINKS = [
        { href: 'index.html', icon: 'fa-house', label: 'หน้าหลัก' },
        { href: 'movie.html', icon: 'fa-clapperboard', label: 'หนังที่ชอบ' },
        { href: 'football.html', icon: 'fa-futbol', label: 'ฟุตบอล' },
        { href: 'activities.html', icon: 'fa-calendar-check', label: 'กิจกรรมของฉัน' },
    ];
    // ── สิ้นสุดส่วนที่แก้ไข ────────────────────────────────────────

    // ตรวจจับชื่อไฟล์ปัจจุบัน
    const currentFile = window.location.pathname.split('/').pop() || 'index.html';

    // สร้าง nav items HTML
    const navItemsHTML = NAV_LINKS.map(link => {
        const isActive = link.href === currentFile ? ' class="active"' : '';
        return `<li class="nav-item">
                    <a href="${link.href}"${isActive}><i class="fa-solid ${link.icon}"></i>${link.label}</a>
                </li>`;
    }).join('\n                ');

    // HTML ของ University Header Banner
    const universityHeaderHTML = `<!-- University Header Banner (generated by navbar.js) -->
    <div class="university-header">
        <div class="uni-header-inner">
            <div class="uni-header-left">
                <div class="uni-logo-icon"><i class="fa-solid fa-graduation-cap"></i></div>
                <div class="uni-header-text">
                    <span class="uni-name">Naresuan University</span>
                    <span class="uni-faculty">Faculty of Science • Information Technology</span>
                </div>
            </div>
            <div class="uni-semester-badge"><i class="fa-solid fa-circle"></i> ภาคเรียนที่ 2 / 2568</div>
        </div>
    </div>`;

    // HTML ของ navbar ทั้งหมด
    const navbarHTML = `<!-- Navbar (generated by navbar.js) -->
    <nav class="navbar">
        <div class="nav-container">
            <a href="${NAV_BRAND.href}" class="logo">
                <i class="fa-solid ${NAV_BRAND.icon}"></i>
                <span>${NAV_BRAND.name}</span>
            </a>
            <ul class="nav-menu">
                ${navItemsHTML}
            </ul>
        </div>
    </nav>`;

    // แทนที่ placeholder ด้วย University Header และ navbar จริง
    const placeholder = document.getElementById('navbar-placeholder');
    if (placeholder) {
        placeholder.outerHTML = universityHeaderHTML + '\n    ' + navbarHTML;
    }
})();
